# Thông tin dự án lấy từ ảnh bạn gửi
sonar.projectKey=Galaxyeye107_aws-eks-cloud-native-devsecops
sonar.organization=galaxyeye107

# Chỉ định các thư mục cần quét
sonar.sources=.
sonar.exclusions=**/test/**, **/node_modules/**, **/*.spec.ts

# Cấu hình riêng cho Java (Backend)
sonar.java.binaries=02-backend/target/classes

# Cấu hình cho TypeScript/Angular (Frontend)
sonar.javascript.node.maxspace=4096
sonar.typescript.tsconfigPath=03-frontend/tsconfig.json