# Bóp tài nguyên xuống mức tối thiểu cho Lab
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

certController:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

installCRDs: true # Ép Helm phải cài đặt các định nghĩa SecretStore, ExternalSecret