apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds-sync
  namespace: default
spec:
  refreshInterval: 1h # Tự động cập nhật lại mỗi 1 tiếng nếu trên AWS có đổi mật khẩu 
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mysql-secrets # Tên secret cuối cùng mà App sẽ sử dụng để lấy username/password
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: prod/ecommerce/db-creds
      property: username
  - secretKey: password
    remoteRef:
      key: prod/ecommerce/db-creds
      property: password