apiVersion: v1
kind: Service
metadata:
  name: mysql-service # GIỮ NGUYÊN TÊN NÀY để Backend không bị lỗi kết nối
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None # Chuyển thành Headless Service để tối ưu cho StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet # CHUYỂN TỪ Deployment SANG StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql-service" # Phải khớp với tên Service ở trên
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_DATABASE
          value: full-stack-ecommerce
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-data # GẮN THÊM VOLUME NÀY
          mountPath: /var/lib/mysql # Đây là nơi dữ liệu thực được lưu
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: init-scripts
        configMap:
          name: mysql-init-scripts
  # ĐÂY LÀ PHẦN QUAN TRỌNG NHẤT: TỰ ĐỘNG TẠO Ổ ĐĨA EBS
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" # Phải trùng với tên StorageClass bạn tạo ở bước tiếp theo
      resources:
        requests:
          storage: 1Gi