apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-sa
  namespace: default
  annotations:
    # THAY THẾ ARN DƯỚI ĐÂY BẰNG ARN BẠN LẤY TỪ TERRAFORM OUTPUT
    eks.amazonaws.com/role-arn: arn:aws:iam::837497587440:role/eks-secrets-manager-role