name: "App - Deploy to EKS"

on:
  workflow_dispatch: # Cho phép bấm nút chạy thủ công
  push:
    paths:
      - 'kubernetes/**' # Tự động chạy khi bạn sửa file manifest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region ap-southeast-1 --name devsecops-eks-cluster

      - name: Enable EKS Network Policy Support
        run: |
          kubectl patch daemonset aws-node -n kube-system --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/env/-", "value": {"name": "NETWORK_POLICY_ENFORCING_MODE", "value": "standard"}}]'
      
      - name: Deploy Manifests
        run: |
          # Áp dụng tất cả các file trong thư mục kubernetes theo thứ tự
          kubectl apply -f kubernetes/service-account.yaml
          kubectl apply -f kubernetes/secret-store.yaml
          kubectl apply -f kubernetes/external-secret.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/ingress.yaml
          kubectl apply -f kubernetes/mysql-configmap.yaml
          kubectl apply -f kubernetes/mysql.yaml
          kubectl apply -f kubernetes/backend-hpa.yaml
          kubectl apply -f kubernetes/storage-class.yaml
          kubectl apply -f kubernetes/network-policy.yaml